print('5 >= 5 :', 5 >= 5)
print('10 == 9 :', 10 == 9)
print("5 != '5' :", 5 != '5')
print("10 == '10' :", 10 == '10')
print('hello == hello :', 'hello' == 'hello')
print("'hello' == 'Hello' or 5 == 6 :", 'hello' == 'Hello' or 5 == 6)
print("('hello' == 'Hello') or (5 == 5) and True :", ('hello' == 'Hello') or (5 == 5) and True)
print("('hello' == 'Hello') or (5 == 5) and ('8' == '8') :", ('hello' == 'Hello') or (5 == 5) and ('8' == '8'))
print("('hello' == 'Hello') or (5 == 5) and ('8' != '8') :", ('hello' == 'Hello') or (5 == 5) and ('8' != '8'))
